// Code generated by "shoutrrr-gen "; DO NOT EDIT.
package pushbullet

import (
	"fmt"
	"net/url"

	"github.com/containrrr/shoutrrr/pkg/conf"
	"github.com/containrrr/shoutrrr/pkg/types"
)

// (‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾)
//  )  Props                          (
// (___________________________________)

type Config struct {
	Targets []string `url:"path" `
	Title   string   `key:"title" `
	Token   string   `url:"host" `
}

type configProp int

const (
	propTargets configProp = 0
	propTitle   configProp = 1
	propToken   configProp = 2
	propCount              = 3
)

var propInfo = types.ConfigPropInfo{
	PropNames: []string{
		"Targets",
		"Title",
		"Token",
	},

	// Note that propKeys may not align with propNames, as a property can have no or multiple keys
	Keys: []string{
		"title",
	},

	DefaultValues: []string{
		"",
		"Shoutrrr notification",
		"",
	},

	PrimaryKeys: []int{
		-1,
		0,
		-1,
	},

	KeyPropIndexes: map[string]int{
		"title": 1,
	},
}

func (_ *Config) PropInfo() *types.ConfigPropInfo {
	return &propInfo
}

// (‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾)
//  )  GetURL                         (
// (___________________________________)

// GetURL returns a URL representation of it's current field values
func (config *Config) GetURL() *url.URL {
	return &url.URL{
		// Userinfo fields are not used for configuration
		Host:     config.Token,
		Path:     conf.JoinPath(config.Targets...),
		RawQuery: conf.QueryValues(config).Encode(),
		Scheme:   Scheme,
	}
}

// (‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾)
//  )  SetURL                         (
// (___________________________________)

// SetURL updates a ServiceConfig from a URL representation of it's field values
func (config *Config) SetURL(configURL *url.URL) error {
	if lc, ok := (interface{})(config).(types.ConfigWithLegacyURLSupport); ok {
		configURL = lc.UpdateLegacyURL(configURL)
	}
	updates := make(map[int]string, propCount)
	updates[int(propToken)] = configURL.Hostname()
	updates[int(propTargets)] = configURL.Path

	for key, value := range configURL.Query() {

		if propIndex, found := propInfo.PropIndexFor(key); found {
			updates[propIndex] = value[0]
		} else if key != "title" {
			return fmt.Errorf("invalid key %q", key)
		}
	}

	err := config.Update(updates)
	if err != nil {
		return err
	}

	if len(config.Targets) == 0 {
		return fmt.Errorf("targets missing from config URL")
	}

	if len(config.Token) != 34 {
		return fmt.Errorf("value %q for token is not the correct length (34)", config.Token)
	}

	if config.Token == "" {
		return fmt.Errorf("token missing from config URL")
	}

	return nil
}

// (‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾)
//  )  Enums / Options                (
// (___________________________________)

func (config *Config) Enums() map[string]types.EnumFormatter {
	return map[string]types.EnumFormatter{}
}

// Update updates the Config from a map of it's properties
func (config *Config) Update(updates map[int]string) error {
	var last_err error
	for index, value := range updates {
		switch configProp(index) {
		case propTargets:
			if val, err := conf.ParsePathListValue(value); err != nil {
				last_err = err
			} else {
				config.Targets = val
			}
		case propTitle:
			if val, err := conf.ParseTextValue(value); err != nil {
				last_err = err
			} else {
				config.Title = val
			}
		case propToken:
			if val, err := conf.ParseTextValue(value); err != nil {
				last_err = err
			} else {
				config.Token = val
			}
		default:
			return fmt.Errorf("invalid key")
		}
		if last_err != nil {
			return fmt.Errorf("failed to set value for %v: %v", propInfo.PropNames[index], last_err)
		}
	}
	return nil
}

// Update updates the Config from a map of it's properties
func (config *Config) PropValue(prop int) string {
	switch configProp(prop) {
	case propTargets:
		return conf.FormatListValue(config.Targets, ",")
	case propTitle:
		return conf.FormatTextValue(config.Title)
	case propToken:
		return conf.FormatTextValue(config.Token)
	default:
		return ""
	}
}
