// Code generated by "shoutrrr-gen --lang go"; DO NOT EDIT.
package pushover

import (
	"fmt"
	"net/url"
	_ "strings"

	"github.com/containrrr/shoutrrr/pkg/conf"
	"github.com/containrrr/shoutrrr/pkg/types"
)

// (‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾)
//  )  Props                          (
// (___________________________________)

type Config struct {
	Devices  []string `key:"devices" `
	Priority int64    `key:"priority" `
	Title    string   `key:"title" `
	Token    string   `url:"password" `
	User     string   `url:"host" `
}

type configProp int

const (
	propDevices  configProp = 0
	propPriority configProp = 1
	propTitle    configProp = 2
	propToken    configProp = 3
	propUser     configProp = 4
	propCount               = 5
)

var propInfo = types.ConfigPropInfo{
	PropNames: []string{
		"Devices",
		"Priority",
		"Title",
		"Token",
		"User",
	},

	// Note that propKeys may not align with propNames, as a property can have no or multiple keys
	Keys: []string{
		"devices",
		"priority",
		"title",
	},

	DefaultValues: []string{
		"",
		"0",
		"",
		"",
		"",
	},

	PrimaryKeys: []int{
		0,
		1,
		2,
		-1,
		-1,
	},

	KeyPropIndexes: map[string]int{
		"devices":  0,
		"priority": 1,
		"title":    2,
	},
}

func (_ *Config) PropInfo() *types.ConfigPropInfo {
	return &propInfo
}

// (‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾)
//  )  GetURL                         (
// (___________________________________)

// GetURL returns a URL representation of it's current field values
func (config *Config) GetURL() *url.URL {
	return &url.URL{
		User:     conf.UserInfoOrNil(url.UserPassword("", config.Token)),
		Host:     config.User,
		Path:     "",
		RawQuery: conf.QueryValues(config).Encode(),
		Scheme:   Scheme,
	}
}

// (‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾)
//  )  SetURL                         (
// (___________________________________)

// SetURL updates a ServiceConfig from a URL representation of it's field values
func (config *Config) SetURL(configURL *url.URL) error {
	if lc, ok := (interface{})(config).(types.ConfigWithLegacyURLSupport); ok {
		configURL = lc.UpdateLegacyURL(configURL)
	}
	updates := make(map[int]string, propCount)
	updates[int(propUser)] = configURL.Hostname()
	if pwd, found := configURL.User.Password(); found {
		updates[int(propToken)] = pwd
	}
	if configURL.Path != "" && configURL.Path != "/" {
		return fmt.Errorf("unexpected path in config URL: %v", configURL.Path)
	}

	for key, value := range configURL.Query() {

		if propIndex, found := propInfo.PropIndexFor(key); found {
			updates[propIndex] = value[0]
		} else if key != "title" {
			return fmt.Errorf("invalid key %q", key)
		}
	}

	err := config.Update(updates)
	if err != nil {
		return err
	}

	if config.Token == "" {
		return fmt.Errorf("token missing from config URL")
	}

	if config.User == "" {
		return fmt.Errorf("user missing from config URL")
	}

	return nil
}

// (‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾)
//  )  Enums / Options                (
// (___________________________________)

func (config *Config) Enums() map[string]types.EnumFormatter {
	return map[string]types.EnumFormatter{}
}

// Update updates the Config from a map of it's properties
func (config *Config) Update(updates map[int]string) error {
	var last_err error
	for index, value := range updates {
		switch configProp(index) {
		case propDevices:
			if val, err := conf.ParseListValue(value, ","); err != nil {
				last_err = err
			} else {
				config.Devices = val
			}
		case propPriority:
			if val, err := conf.ParseNumberValue(value, 10); err != nil {
				last_err = err
			} else {
				config.Priority = val
			}
		case propTitle:
			if val, err := conf.ParseTextValue(value); err != nil {
				last_err = err
			} else {
				config.Title = val
			}
		case propToken:
			if val, err := conf.ParseTextValue(value); err != nil {
				last_err = err
			} else {
				config.Token = val
			}
		case propUser:
			if val, err := conf.ParseTextValue(value); err != nil {
				last_err = err
			} else {
				config.User = val
			}
		default:
			return fmt.Errorf("invalid key")
		}
		if last_err != nil {
			return fmt.Errorf("failed to set value for %v: %v", propInfo.PropNames[index], last_err)
		}
	}
	return nil
}

// Update updates the Config from a map of it's properties
func (config *Config) PropValue(prop int) string {
	switch configProp(prop) {
	case propDevices:
		return conf.FormatListValue(config.Devices, ",")
	case propPriority:
		return conf.FormatNumberValue(config.Priority, 10)
	case propTitle:
		return conf.FormatTextValue(config.Title)
	case propToken:
		return conf.FormatTextValue(config.Token)
	case propUser:
		return conf.FormatTextValue(config.User)
	default:
		return ""
	}
}
