// Code generated by "shoutrrr-gen "; DO NOT EDIT.
package join

import (
	"fmt"
	"net/url"

	"github.com/containrrr/shoutrrr/pkg/conf"
	"github.com/containrrr/shoutrrr/pkg/types"
)

// (‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾)
//  )  Props                          (
// (___________________________________)

type Config struct {
	APIKey  string   `url:"password" `
	Devices []string `key:"devices" `
	Host    string   `url:"host" `
	Icon    string   `key:"icon" `
	Path    string   `url:"path" `
	Title   string   `key:"title" `
}

type configProp int

const (
	propAPIKey  configProp = 0
	propDevices configProp = 1
	propHost    configProp = 2
	propIcon    configProp = 3
	propPath    configProp = 4
	propTitle   configProp = 5
	propCount              = 6
)

var propInfo = types.ConfigPropInfo{
	PropNames: []string{
		"APIKey",
		"Devices",
		"Host",
		"Icon",
		"Path",
		"Title",
	},

	// Note that propKeys may not align with propNames, as a property can have no or multiple keys
	Keys: []string{
		"devices",
		"icon",
		"title",
	},

	DefaultValues: []string{
		"",
		"",
		"join",
		"",
		"",
		"",
	},

	PrimaryKeys: []int{
		-1,
		0,
		-1,
		1,
		-1,
		2,
	},

	KeyPropIndexes: map[string]int{
		"devices": 1,
		"icon":    3,
		"title":   5,
	},
}

func (_ *Config) PropInfo() *types.ConfigPropInfo {
	return &propInfo
}

// (‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾)
//  )  GetURL                         (
// (___________________________________)

// GetURL returns a URL representation of it's current field values
func (config *Config) GetURL() *url.URL {
	return &url.URL{
		User:     conf.UserInfoOrNil(url.UserPassword("", config.APIKey)),
		Host:     config.Host,
		Path:     conf.JoinPath(string(config.Path)),
		RawQuery: conf.QueryValues(config).Encode(),
		Scheme:   Scheme,
	}
}

// (‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾)
//  )  SetURL                         (
// (___________________________________)

// SetURL updates a ServiceConfig from a URL representation of it's field values
func (config *Config) SetURL(configURL *url.URL) error {
	if lc, ok := (interface{})(config).(types.ConfigWithLegacyURLSupport); ok {
		configURL = lc.UpdateLegacyURL(configURL)
	}
	updates := make(map[int]string, propCount)
	updates[int(propHost)] = configURL.Hostname()
	if pwd, found := configURL.User.Password(); found {
		updates[int(propAPIKey)] = pwd
	}
	updates[int(propPath)] = configURL.Path

	for key, value := range configURL.Query() {

		if propIndex, found := propInfo.PropIndexFor(key); found {
			updates[propIndex] = value[0]
		} else if key != "title" {
			return fmt.Errorf("invalid key %q", key)
		}
	}

	err := config.Update(updates)
	if err != nil {
		return err
	}

	if config.APIKey == "" {
		return fmt.Errorf("apiKey missing from config URL")
	}

	if len(config.Devices) == 0 {
		return fmt.Errorf("devices missing from config URL")
	}

	return nil
}

// (‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾)
//  )  Enums / Options                (
// (___________________________________)

func (config *Config) Enums() map[string]types.EnumFormatter {
	return map[string]types.EnumFormatter{}
}

// Update updates the Config from a map of it's properties
func (config *Config) Update(updates map[int]string) error {
	var last_err error
	for index, value := range updates {
		switch configProp(index) {
		case propAPIKey:
			if val, err := conf.ParseTextValue(value); err != nil {
				last_err = err
			} else {
				config.APIKey = val
			}
		case propDevices:
			if val, err := conf.ParseListValue(value, ","); err != nil {
				last_err = err
			} else {
				config.Devices = val
			}
		case propHost:
			if val, err := conf.ParseTextValue(value); err != nil {
				last_err = err
			} else {
				config.Host = val
			}
		case propIcon:
			if val, err := conf.ParseTextValue(value); err != nil {
				last_err = err
			} else {
				config.Icon = val
			}
		case propPath:
			if val, err := conf.ParseTextValue(value); err != nil {
				last_err = err
			} else {
				config.Path = val
			}
		case propTitle:
			if val, err := conf.ParseTextValue(value); err != nil {
				last_err = err
			} else {
				config.Title = val
			}
		default:
			return fmt.Errorf("invalid key")
		}
		if last_err != nil {
			return fmt.Errorf("failed to set value for %v: %v", propInfo.PropNames[index], last_err)
		}
	}
	return nil
}

// Update updates the Config from a map of it's properties
func (config *Config) PropValue(prop int) string {
	switch configProp(prop) {
	case propAPIKey:
		return conf.FormatTextValue(config.APIKey)
	case propDevices:
		return conf.FormatListValue(config.Devices, ",")
	case propHost:
		return conf.FormatTextValue(config.Host)
	case propIcon:
		return conf.FormatTextValue(config.Icon)
	case propPath:
		return conf.FormatTextValue(config.Path)
	case propTitle:
		return conf.FormatTextValue(config.Title)
	default:
		return ""
	}
}
