// Code generated by "shoutrrr-gen "; DO NOT EDIT.
package gotify

import (
	"fmt"
	"net/url"

	"github.com/containrrr/shoutrrr/pkg/conf"
	"github.com/containrrr/shoutrrr/pkg/types"
)

// (‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾)
//  )  Props                          (
// (___________________________________)

type Config struct {
	DisableTLS bool   `key:"disabletls" `
	Host       string `url:"host,port" `
	Path       string `url:"path" `
	Priority   int64  `key:"priority" `
	Title      string `key:"title" `
	Token      string `url:"path1" `
}

type configProp int

const (
	propDisableTLS configProp = 0
	propHost       configProp = 1
	propPath       configProp = 2
	propPriority   configProp = 3
	propTitle      configProp = 4
	propToken      configProp = 5
	propCount                 = 6
)

var propInfo = types.ConfigPropInfo{
	PropNames: []string{
		"DisableTLS",
		"Host",
		"Path",
		"Priority",
		"Title",
		"Token",
	},

	// Note that propKeys may not align with propNames, as a property can have no or multiple keys
	Keys: []string{
		"disabletls",
		"priority",
		"title",
	},

	DefaultValues: []string{
		"No",
		"",
		"",
		"0",
		"Shoutrrr notification",
		"",
	},

	PrimaryKeys: []int{
		0,
		-1,
		-1,
		1,
		2,
		-1,
	},

	KeyPropIndexes: map[string]int{
		"disabletls": 0,
		"priority":   3,
		"title":      4,
	},
}

func (_ *Config) PropInfo() *types.ConfigPropInfo {
	return &propInfo
}

// (‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾)
//  )  GetURL                         (
// (___________________________________)

// GetURL returns a URL representation of it's current field values
func (config *Config) GetURL() *url.URL {
	return &url.URL{
		// Userinfo fields are not used for configuration
		Host:     config.Host,
		Path:     conf.JoinPath(string(config.Path), string(config.Token)),
		RawQuery: conf.QueryValues(config).Encode(),
		Scheme:   Scheme,
	}
}

// (‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾)
//  )  SetURL                         (
// (___________________________________)

// SetURL updates a ServiceConfig from a URL representation of it's field values
func (config *Config) SetURL(configURL *url.URL) error {
	if lc, ok := (interface{})(config).(types.ConfigWithLegacyURLSupport); ok {
		configURL = lc.UpdateLegacyURL(configURL)
	}
	updates := make(map[int]string, propCount)
	updates[int(propHost)] = configURL.Host

	pathParts := conf.SplitPath(configURL.Path)
	if len(pathParts) > 0 {
		updates[int(propToken)] = pathParts[len(pathParts)-1]
	}
	if len(pathParts) > 1 {
		updates[int(propPath)] = conf.JoinPath(pathParts[:len(pathParts)-1]...)
	}

	for key, value := range configURL.Query() {

		if propIndex, found := propInfo.PropIndexFor(key); found {
			updates[propIndex] = value[0]
		} else if key != "title" {
			return fmt.Errorf("invalid key %q", key)
		}
	}

	err := config.Update(updates)
	if err != nil {
		return err
	}

	if config.Host == "" {
		return fmt.Errorf("host missing from config URL")
	}

	if config.Token == "" {
		return fmt.Errorf("token missing from config URL")
	}

	return nil
}

// (‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾)
//  )  Enums / Options                (
// (___________________________________)

func (config *Config) Enums() map[string]types.EnumFormatter {
	return map[string]types.EnumFormatter{}
}

// Update updates the Config from a map of it's properties
func (config *Config) Update(updates map[int]string) error {
	var last_err error
	for index, value := range updates {
		switch configProp(index) {
		case propDisableTLS:
			if val, err := conf.ParseToggleValue(value); err != nil {
				last_err = err
			} else {
				config.DisableTLS = val
			}
		case propHost:
			if val, err := conf.ParseTextValue(value); err != nil {
				last_err = err
			} else {
				config.Host = val
			}
		case propPath:
			if val, err := conf.ParseTextValue(value); err != nil {
				last_err = err
			} else {
				config.Path = val
			}
		case propPriority:
			if val, err := conf.ParseNumberValue(value, 10); err != nil {
				last_err = err
			} else {
				config.Priority = val
			}
		case propTitle:
			if val, err := conf.ParseTextValue(value); err != nil {
				last_err = err
			} else {
				config.Title = val
			}
		case propToken:
			if val, err := conf.ParseTextValue(value); err != nil {
				last_err = err
			} else {
				config.Token = val
			}
		default:
			return fmt.Errorf("invalid key")
		}
		if last_err != nil {
			return fmt.Errorf("failed to set value for %v: %v", propInfo.PropNames[index], last_err)
		}
	}
	return nil
}

// Update updates the Config from a map of it's properties
func (config *Config) PropValue(prop int) string {
	switch configProp(prop) {
	case propDisableTLS:
		return conf.FormatToggleValue(config.DisableTLS)
	case propHost:
		return conf.FormatTextValue(config.Host)
	case propPath:
		return conf.FormatTextValue(config.Path)
	case propPriority:
		return conf.FormatNumberValue(config.Priority, 10)
	case propTitle:
		return conf.FormatTextValue(config.Title)
	case propToken:
		return conf.FormatTextValue(config.Token)
	default:
		return ""
	}
}
