// Code generated by "shoutrrr-gen --lang go"; DO NOT EDIT.
package teams

import (
	"fmt"
	"net/url"
	_ "strings"

	"github.com/containrrr/shoutrrr/pkg/conf"
	"github.com/containrrr/shoutrrr/pkg/types"
)

// (‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾)
//  )  Props                          (
// (___________________________________)

type Config struct {
	AltID      string `url:"path1" `
	Color      string `key:"color" `
	Group      string `url:"user" `
	GroupOwner string `url:"path2" `
	Host       string `key:"host" `
	Tenant     string `url:"host" `
	Title      string `key:"title" `
}

type configProp int

const (
	propAltID      configProp = 0
	propColor      configProp = 1
	propGroup      configProp = 2
	propGroupOwner configProp = 3
	propHost       configProp = 4
	propTenant     configProp = 5
	propTitle      configProp = 6
	propCount                 = 7
)

var propInfo = types.ConfigPropInfo{
	PropNames: []string{
		"AltID",
		"Color",
		"Group",
		"GroupOwner",
		"Host",
		"Tenant",
		"Title",
	},

	// Note that propKeys may not align with propNames, as a property can have no or multiple keys
	Keys: []string{
		"color",
		"host",
		"title",
	},

	DefaultValues: []string{
		"",
		"",
		"",
		"",
		"outlook.office.com",
		"",
		"",
	},

	PrimaryKeys: []int{
		-1,
		0,
		-1,
		-1,
		1,
		-1,
		2,
	},

	KeyPropIndexes: map[string]int{
		"color": 1,
		"host":  4,
		"title": 6,
	},
}

func (_ *Config) PropInfo() *types.ConfigPropInfo {
	return &propInfo
}

// (‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾)
//  )  GetURL                         (
// (___________________________________)

// GetURL returns a URL representation of it's current field values
func (config *Config) GetURL() *url.URL {
	return &url.URL{
		User:     conf.UserInfoOrNil(url.User(config.Group)),
		Host:     config.Tenant,
		Path:     conf.JoinPath(string(config.AltID), string(config.GroupOwner)),
		RawQuery: conf.QueryValues(config).Encode(),
		Scheme:   Scheme,
	}
}

// (‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾)
//  )  SetURL                         (
// (___________________________________)

// SetURL updates a ServiceConfig from a URL representation of it's field values
func (config *Config) SetURL(configURL *url.URL) error {
	if lc, ok := (interface{})(config).(types.ConfigWithLegacyURLSupport); ok {
		configURL = lc.UpdateLegacyURL(configURL)
	}
	updates := make(map[int]string, propCount)
	updates[int(propTenant)] = configURL.Hostname()
	updates[int(propGroup)] = configURL.User.Username()

	pathParts := conf.SplitPath(configURL.Path)
	if len(pathParts) > 0 {
		updates[int(propAltID)] = pathParts[0]
	}
	if len(pathParts) > 1 {
		updates[int(propGroupOwner)] = pathParts[1]
	}
	if len(pathParts) > 2 {
		return fmt.Errorf("too many path items: %v, expected 2", len(pathParts))
	}

	for key, value := range configURL.Query() {

		if propIndex, found := propInfo.PropIndexFor(key); found {
			updates[propIndex] = value[0]
		} else if key != "title" {
			return fmt.Errorf("invalid key %q", key)
		}
	}

	err := config.Update(updates)
	if err != nil {
		return err
	}

	return nil
}

// (‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾)
//  )  Enums / Options                (
// (___________________________________)

func (config *Config) Enums() map[string]types.EnumFormatter {
	return map[string]types.EnumFormatter{}
}

// Update updates the Config from a map of it's properties
func (config *Config) Update(updates map[int]string) error {
	var last_err error
	for index, value := range updates {
		switch configProp(index) {
		case propAltID:
			if val, err := conf.ParseTextValue(value); err != nil {
				last_err = err
			} else {
				config.AltID = val
			}
		case propColor:
			if val, err := conf.ParseTextValue(value); err != nil {
				last_err = err
			} else {
				config.Color = val
			}
		case propGroup:
			if val, err := conf.ParseTextValue(value); err != nil {
				last_err = err
			} else {
				config.Group = val
			}
		case propGroupOwner:
			if val, err := conf.ParseTextValue(value); err != nil {
				last_err = err
			} else {
				config.GroupOwner = val
			}
		case propHost:
			if val, err := conf.ParseTextValue(value); err != nil {
				last_err = err
			} else {
				config.Host = val
			}
		case propTenant:
			if val, err := conf.ParseTextValue(value); err != nil {
				last_err = err
			} else {
				config.Tenant = val
			}
		case propTitle:
			if val, err := conf.ParseTextValue(value); err != nil {
				last_err = err
			} else {
				config.Title = val
			}
		default:
			return fmt.Errorf("invalid key")
		}
		if last_err != nil {
			return fmt.Errorf("failed to set value for %v: %v", propInfo.PropNames[index], last_err)
		}
	}
	return nil
}

// Update updates the Config from a map of it's properties
func (config *Config) PropValue(prop int) string {
	switch configProp(prop) {
	case propAltID:
		return conf.FormatTextValue(config.AltID)
	case propColor:
		return conf.FormatTextValue(config.Color)
	case propGroup:
		return conf.FormatTextValue(config.Group)
	case propGroupOwner:
		return conf.FormatTextValue(config.GroupOwner)
	case propHost:
		return conf.FormatTextValue(config.Host)
	case propTenant:
		return conf.FormatTextValue(config.Tenant)
	case propTitle:
		return conf.FormatTextValue(config.Title)
	default:
		return ""
	}
}
