name: shoutrrr 
base: core22 
version: '0.6.1' 
summary: Sending notifications made easy. 
description: |
  Shoutrrr is a way of making the sending of notifications easy by standardizing it.
grade: stable 
confinement: strict 
contact: https://github.com/containrrr/shoutrrr/discussions
issues: https://github.com/containrrr/shoutrrr/issues
icon: docs/shoutrrr-logotype.png
license: MIT
source-code: https://github.com/containrrr/shoutrrr
type: app
compression: lzo

plugs:
  - network

apps:
  shoutrrr:
    command: bin/shoutrrr

parts:
  shoutrrr:
    plugin: go
    source: . 
    source-type: git
    build-packages:
      - golang
    build-environment:
      - CGO_ENABLED: 0

